# Giant TNT Mod - Adds massive explosive TNT for Minecraft
# Author: Shengbo Jiang
# License: MIT License

modLoader="javafml"
loaderVersion="[43,)"
license="MIT License - Free to use, modify, and distribute"
issueTrackerURL="https://github.com/shengbojiang/minecraft-giant-tnt-mod/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="gianttntmod" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Giant TNT Mod" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/shengbojiang/minecraft-giant-tnt-mod"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="gianttnt_logo.png"
# A text field displayed in the mod UI
credits="Thanks to the Minecraft Forge team for making modding possible!"
# A text field displayed in the mod UI
authors="Shengbo Jiang"
# The description text for the mod (multi line text here _is_ allowed)
description='''
Giant TNT Mod adds massive explosive TNT for epic destruction in Minecraft!

Features:
- Giant TNT that flies high into the air before exploding
- Configurable explosion radius (default: 650-block diameter craters)
- Performance-optimized phased explosions to prevent server lag
- Configurable particle effects and explosion parameters
- Realistic physics with ground impact detection

Perfect for creative mode builds, clearing large areas, or just having fun with massive explosions!
Includes performance modes to ensure smooth gameplay on all servers.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.gianttntmod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[43,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.gianttntmod]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to the next major version of Minecraft.
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH" 